title: jekyll-hashsert
description: >-
  jekyll-hashsert is a jekyll plugin that exposes a liquid filter which generates random alphanumeric hashes of custom length and inserts them into specific positions in an input string.
url: "https://hashsert.gouravkhunger.me"
baseurl: ""

author:
  name: Gourav Khunger
  email: gouravkhunger18[at]gmail.com

remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: github,  user_url: "https://link.gouravkhunger.me/github" }
    - { platform: youtube, user_url: "https://link.gouravkhunger.me/youtube" }
    - { platform: twitter, user_url: "https://link.gouravkhunger.me/twitter" }
    - { platform: stackoverflow, user_url: "https://link.gouravkhunger.me/stackoverflow" }

plugins:
  - jekyll-hashsert
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
